version: '3.9'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-7001}  # Railways will provide this
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "${PORT:-7001}:${PORT:-7001}"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${PORT:-7001}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=5173
      - VITE_WS_BACKEND_URL=${RAILWAY_STATIC_URL:-http://backend:7001}
    ports:
      - "5173:5173"
    depends_on:
      - backend
